"""
reasoning/models.py — Data classes for the CARL Reasoning Engine.

All structured types used across the reasoning package are defined here
to avoid circular imports and keep a single source of truth.
"""
from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


# ── Execution Level ──────────────────────────────────────────────────────────

class ExecutionLevel(Enum):
    """Determines how a command should be processed."""
    SINGLE = "single"       # One tool call — bypass planner entirely
    PLAN = "plan"           # Multi-step plan (2-8 steps)
    MISSION = "mission"     # Long-running task (future: survives reconnects)
    CLARIFY = "clarify"     # Confidence too low — ask user for details


# ── Step Status ──────────────────────────────────────────────────────────────

class StepStatus(Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    RETRYING = "retrying"
    SKIPPED = "skipped"
    AWAITING_CONFIRMATION = "awaiting_confirmation"


# ── Retry Policy ─────────────────────────────────────────────────────────────

@dataclass
class RetryPolicy:
    max_retries: int = 2
    backoff_sec: float = 1.0


# ── Step ─────────────────────────────────────────────────────────────────────

@dataclass
class Step:
    """A single step in a plan."""
    id: str
    description: str
    capability: str                          # e.g. "list_files", "delete_files", "open_browser"
    arguments: dict[str, Any] = field(default_factory=dict)
    dependencies: list[str] = field(default_factory=list)
    retry_policy: RetryPolicy = field(default_factory=RetryPolicy)
    requires_confirmation: bool = False      # set by Safety Validator
    status: StepStatus = StepStatus.PENDING
    result: str = ""
    error: str = ""
    retries_used: int = 0
    started_at: float = 0.0
    completed_at: float = 0.0

    @property
    def duration_sec(self) -> float:
        if self.started_at and self.completed_at:
            return self.completed_at - self.started_at
        return 0.0

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "description": self.description,
            "capability": self.capability,
            "arguments": self.arguments,
            "dependencies": self.dependencies,
            "retry_policy": {
                "max_retries": self.retry_policy.max_retries,
                "backoff_sec": self.retry_policy.backoff_sec,
            },
            "requires_confirmation": self.requires_confirmation,
            "status": self.status.value,
            "result": self.result,
            "error": self.error,
            "retries_used": self.retries_used,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Step":
        rp = data.get("retry_policy", {})
        return cls(
            id=data["id"],
            description=data.get("description", ""),
            capability=data.get("capability", ""),
            arguments=data.get("arguments", {}),
            dependencies=data.get("dependencies", []),
            retry_policy=RetryPolicy(
                max_retries=rp.get("max_retries", 2),
                backoff_sec=rp.get("backoff_sec", 1.0),
            ),
            requires_confirmation=data.get("requires_confirmation", False),
            status=StepStatus(data.get("status", "pending")),
        )


# ── Plan ─────────────────────────────────────────────────────────────────────

@dataclass
class Plan:
    """A structured multi-step plan generated by the Planner."""
    goal: str
    confidence: float                        # 0.0 – 1.0
    steps: list[Step] = field(default_factory=list)
    estimated_duration_sec: float = 0.0
    created_at: float = field(default_factory=time.time)

    @property
    def total_steps(self) -> int:
        return len(self.steps)

    @property
    def completed_steps(self) -> int:
        return sum(1 for s in self.steps if s.status == StepStatus.COMPLETED)

    @property
    def failed_steps(self) -> int:
        return sum(1 for s in self.steps if s.status == StepStatus.FAILED)

    @property
    def progress_pct(self) -> float:
        if not self.steps:
            return 0.0
        return (self.completed_steps / self.total_steps) * 100.0

    @property
    def current_step(self) -> Step | None:
        for s in self.steps:
            if s.status in (StepStatus.RUNNING, StepStatus.RETRYING):
                return s
        for s in self.steps:
            if s.status == StepStatus.PENDING:
                return s
        return None

    @property
    def is_complete(self) -> bool:
        return all(
            s.status in (StepStatus.COMPLETED, StepStatus.SKIPPED, StepStatus.FAILED)
            for s in self.steps
        )

    @property
    def is_successful(self) -> bool:
        return self.is_complete and self.failed_steps == 0

    def to_dict(self) -> dict:
        return {
            "goal": self.goal,
            "confidence": self.confidence,
            "estimated_duration_sec": self.estimated_duration_sec,
            "created_at": self.created_at,
            "steps": [s.to_dict() for s in self.steps],
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Plan":
        return cls(
            goal=data["goal"],
            confidence=data.get("confidence", 0.5),
            steps=[Step.from_dict(s) for s in data.get("steps", [])],
            estimated_duration_sec=data.get("estimated_duration_sec", 0.0),
            created_at=data.get("created_at", time.time()),
        )


# ── Plan Result ──────────────────────────────────────────────────────────────

@dataclass
class PlanResult:
    """Final outcome after executing a plan."""
    success: bool
    summary: str
    plan: Plan
    duration_sec: float = 0.0
    tools_used: list[str] = field(default_factory=list)
    total_retries: int = 0


# ── Mission Record ───────────────────────────────────────────────────────────

@dataclass
class MissionRecord:
    """Persistent record of a completed plan for history/learning."""
    goal: str
    started_at: float
    completed_at: float
    duration_sec: float
    success: bool
    confidence: float
    total_steps: int
    completed_steps: int
    failed_steps: int
    tools_used: list[str]
    total_retries: int
    summary: str

    def to_dict(self) -> dict:
        return {
            "goal": self.goal,
            "started_at": self.started_at,
            "completed_at": self.completed_at,
            "duration_sec": round(self.duration_sec, 2),
            "success": self.success,
            "confidence": self.confidence,
            "total_steps": self.total_steps,
            "completed_steps": self.completed_steps,
            "failed_steps": self.failed_steps,
            "tools_used": self.tools_used,
            "total_retries": self.total_retries,
            "summary": self.summary,
        }

    @classmethod
    def from_plan_result(cls, result: PlanResult) -> "MissionRecord":
        plan = result.plan
        return cls(
            goal=plan.goal,
            started_at=plan.created_at,
            completed_at=time.time(),
            duration_sec=result.duration_sec,
            success=result.success,
            confidence=plan.confidence,
            total_steps=plan.total_steps,
            completed_steps=plan.completed_steps,
            failed_steps=plan.failed_steps,
            tools_used=result.tools_used,
            total_retries=result.total_retries,
            summary=result.summary,
        )
